### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by yofukashino** [romdotdog/wpm#3]
starts in hundred and then goes to zero slowly even if i am typing

**Comment by romdotdog** [comment]
I can't reproduce. When you're typing, are you using spaces to separate words?

**Comment by yofukashino** [comment]
> I can't reproduce. When you're typing, are you using spaces to separate words?

who dont?

**Comment by yofukashino** [comment]
but shouldnt it go to zero even if am not typing? like can you add a check interval to it, so that it wouldnt just depend on user typing but keep checking itself idk,

**Comment by romdotdog** [comment]
Why would it update your WPM when you're not typing? You wouldn't get a chance to see your true WPM.

**Comment by yofukashino** [comment]
It should reduce by time if not typing because it's how you measure wpm else it's not live wpm

**Comment by romdotdog** [comment]
This is what the plugin does already. I'm closing this issue because I don't see a bug. Feel free to create a fork based on your desired changes.
